### ISSUE TITLE
Set paging = true gives warning

### ISSUE THREAD

**Issue by TimPietrusky** [sinnerschrader/dekk#11] opened 2018-02-21 05:25 UTC
## Issue description
When setting the `paging={true}` I receive this warning in the browser console:
```
Warning: Failed prop type: Invalid prop `paging` of value `true` supplied to `Config`, expected one of [false].
    in Config (created by App)
    in App
```

## Steps to reproduce
* Use the Config component
* Set paging to true: `<Config paging={true} url='hash'/>`

## Versions
1.0.0.-4

1. yarn: 1.3.2
2. node 6.9.1

**Comment by pixelass** [comment] 2018-02-21 11:40
This works as intended. paging is/was enabled per default and can only be disabled by setting it to `false` (experimental/missing in docs)

related to #10

Issue will be closed when #12 is merged

**Closed** 2018-02-21 14:11 UTC
Labels: wontfix
